-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.newsletter
(
    id serial NOT NULL,
    title character varying(256) NOT NULL,
    published date,
    filename character varying NOT NULL,
    teasertext character varying,
    thumbnail_name character varying,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public."user"
(
    email character varying NOT NULL,
    password character varying NOT NULL,
    PRIMARY KEY (email)
    );

CREATE TABLE IF NOT EXISTS public.subscriber
(
    email character varying NOT NULL,
    created date NOT NULL,
    PRIMARY KEY (email)
    );
END;